spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security_app?serverTimezone=Europe/Samara
    username: spring
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
jwt:
  secret: secret
  expired: 3600000